### ISSUE TITLE
Oled

### ISSUE THREAD

**Issue by Roturbo** [haklein/r4850g2_arduino#1]
Hello, 

i try to build this to adjust my r4850 power supply but no joy, display not working.

i have use 4 and 5 for oled SDA and SCL, i have 2 types of oled, the 0.96 and the 1.2" and they are working 
because i try with other sketch.

Example, with sketch SH106-128-64_i2c, ssd1306_128x32_i2c, DisplayRotationWire,  Wire128x64SH1106 the oled works.

Can you please post the schematics for correct connection for oled and can-bus board,  also the type of Oled to use ?

Tanks in advance

.

**Comment by haklein** [comment]
Hi, you do use the `R4850G2_Menu.ino` Sketch, right? Line 42 defines the i2c address of the Oled module. I'm using the 0.96" 1306 one. br Hari

**Comment by Roturbo** [comment]
Hi,

the problem was the missing can module, the software hangs if there is no communication with the
can module and the display stays black,, i have look for the pin out and connect it, and it is working normal.


How about give the option to use the Oled 1.3" SH1106 ?

I leave here the connections,, if you want put it on first page to help others in future.

![r4850G2_pinout](https://github.com/haklein/r4850g2_arduino/assets/91867260/3ad49603-3def-4ec2-9e40-f8289db90cfa)


Regards

**Comment by haklein** [comment]
Thanks a lot, I've added the pinout to the readme! I do not have a SH1106 to test, but feel free to submit a PR.

**Comment by Roturbo** [comment]
Hi, , 

i will open a PR for the SH1106.

The picture is "private-user-images.",, i think you need to save it on you PC and upload it again for everyone to see it on the readme page.

regards.

**Comment by haklein** [comment]
just did that, thanks!

**Comment by Roturbo** [comment]
Hello,

Sorry i don´t have knowledge to make this type of changes and open a PR, my programming skills are very low.

The 1.3" oled is working, one or two vertical lines missing on the left but it is ok,  if you want and have the chance
to change the code i can try it and report here.

![1](https://github.com/haklein/r4850g2_arduino/assets/91867260/a1ecc9ec-9b61-499d-ad15-0feb74eaa4f1)

![2](https://github.com/haklein/r4850g2_arduino/assets/91867260/3868f879-0291-49da-a6f3-e190946c069e)

It´s working,, tank you for this.


Regards.
