### ISSUE TITLE
menu version don't work per default

### ISSUE THREAD

**Issue by dl1bz** [haklein/r4850g2_arduino#2]
The menu version don't work here , I found two problems:
1.
Reason: you forget to initialize the I2C bus:
add 
```
Wire.begin();
Wire.setClock(400000L);
```
in the setup() function before you initialize the OLED, otherwise the 328 will be stopping/hang up.

2.
The second problem: runs not at an Arduino Nano per default.
Reason: compiled code to big for this CPU. You need to reduce code like some serial outputs. Use here the Arduino IDE 2.x with actual versions of all needed libs and using Ardunio Nano V3 from AZ Delivery and the 1,3" OLED display, which need a short patch too:
`oled.begin(&SH1106_128x64, SCREEN_ADDRESS);`

I2C address is in this case 0x3C (most 1.3" OLEDs are using 0x3D) for my display I use.

You can add a short scan routine for checking the I2C bus (helpful for find out the correct address for the used OLED):
```
//-----------------------------------------------------------------------------------------------------
// scan I2C bus for connected devices
void scanI2C() {
  byte error, address;
  int nDevices = 0;

  // Wire.begin();  // if not done before start I2C bus
  Serial.println(F("Scanning for I2C devices ..."));
  for(address = 0x01; address < 0x7f; address++){
    Wire.beginTransmission(address);
    error = Wire.endTransmission();
    if (error == 0){
      Serial.print(F("I2C device found at address 0x"));Serial.println(address,HEX);
      nDevices++;
    } else if(error != 2){
      Serial.print(F("Error "));Serial.print(error);Serial.print(F(" at address 0x"));Serial.println(address,HEX);
    }
  }
  if (nDevices == 0){
    Serial.println(F("No I2C devices found"));
  }
  delay(3000);
}
//-----------------------------------------------------------------------------------------------------
```

After this fixes your program works :)

**Comment by haklein** [comment]
Looking at the examples from the SSD1306Ascii library this didn't seem to be mandatory. Also it did work for me on two different boards (nano and mega2560) and also for other users. Still good to know that this might be required in some situations, so thanks a lot for your comment! I didn't use the Version 2 IDE a lot as I do find PIO & vscode much more convenient. 73
