### ISSUE TITLE
menu.h error

### ISSUE THREAD

**Issue by buddhafragt** [haklein/r4850g2_arduino#3]
Hello, while compiling I always get a error:
.....R4850G2_Menu.ino:130:1: error: 'result' does not name a type
 result persist(eventMask e) {

Do you have a idea, whats wrong? I try different Arduino IDE versions and Arduinomenu versions, but still the same.

**Comment by haklein** [comment]
Works for me, just compiled. Arduino 1.8.19, ArduinoMenu 4.21.4, Board "Arduino Nano".

**Comment by buddhafragt** [comment]
can not find the reason....
maybe the clickencoder library is wrong, which one you use?

**Comment by haklein** [comment]
> can not find the reason.... maybe the clickencoder library is wrong, which one you use?

I think the one from 0xpit, need to check. You could try his `platformio.ini` (move the ino sketch to a directory named `src`):
```
[platformio]

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328

framework=arduino
lib_deps=
	neu-rah/ArduinoMenu library@^4.21.4
	greiman/SSD1306Ascii@^1.3.5
	0xpit/ClickEncoder
	sandeepmistry/CAN@^0.3.1
	paulstoffregen/TimerOne@^1.1.1
```

**Comment by buddhafragt** [comment]
Thanks, I was trying to compile with the ArduinoIDE, this is not working.
With PlatformIO the code compiles. 
Suggestion:
With my board I need to change in the .ini file the board to:
board = nanoatmega328new

**Comment by haklein** [comment]
great to here that this is working for you. Yeah, the board definition needs to match your exact board.
